Add- Navigate Navbar, RoutePath, Route, HomePage
KwinyarutP/SignBloom3D pull request #20
Opened 2024-08-28 04:17 UTC by KwinyarutP

Navigate link in Navbar to other page and fetch api search suggestion.

2024-08-28 04:50 UTC, Mark169Z reviewed
In some parts of the code, you can avoid use redundant class by putting the class in parent div, and some part can be simplified. but overall code is good. Great!

2024-08-28 04:50 UTC, Mark169Z commented on client/src/components/Navbaruser.jsx
>                </div>
Move some classes to parent div

2024-08-28 04:50 UTC, Mark169Z commented on client/src/general/Router.jsx
> +
Okay

2024-08-28 04:50 UTC, Mark169Z commented on client/src/components/Searchbar.jsx
> +    <Combobox value={selectedSearch} onChange={setSelectedSearch}>
I think this one can be simplified. up to you

2024-08-28 05:04 UTC, NANAYEMYINTKYI commented on client/src/pages/home/HomePage.jsx
> +            // filteredSearchResults={filteredSearchResults}
Do you still used filtersearchresult or not ??

2024-08-28 05:06 UTC, NANAYEMYINTKYI commented on client/src/components/Searchbar.jsx
> +        <Combobox.Options>
Suggest to change the variable name person to relate name to the function

2024-08-28 05:08 UTC, NANAYEMYINTKYI approved these changes

2024-08-28 12:33 UTC, KwinyarutP commented on client/src/components/Navbaruser.jsx
>                </div>
done

2024-08-28 12:45 UTC, KwinyarutP commented on client/src/pages/home/HomePage.jsx
> +            // filteredSearchResults={filteredSearchResults}
delete

2024-08-28 14:45 UTC, KwinyarutP commented on client/src/components/Searchbar.jsx
> +    <Combobox value={selectedSearch} onChange={setSelectedSearch}>
done

2024-08-29 15:13 UTC, Chatchaponz requested changes

2024-08-29 15:14 UTC, Chatchaponz approved these changes

2024-08-29 15:14 UTC, merged